// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtahRepeaters.Api.Database;

namespace UtahRepeaters.Api.Migrations
{
    [DbContext(typeof(RepeaterContext))]
    partial class RepeaterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("UtahRepeaters.Api.Database.Models.Coordinates", b =>
                {
                    b.Property<int>("CoordinatesId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Elevation");

                    b.Property<float>("Latitude");

                    b.Property<string>("Location");

                    b.Property<float>("Longitude");

                    b.Property<int>("RepeaterId");

                    b.Property<string>("StateCode");

                    b.HasKey("CoordinatesId");

                    b.HasIndex("RepeaterId")
                        .IsUnique();

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("UtahRepeaters.Api.Database.Models.Repeater", b =>
                {
                    b.Property<int>("RepeaterId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AttributesRepeaterAttributesId");

                    b.Property<int>("Band");

                    b.Property<string>("Callsign");

                    b.Property<string>("Description");

                    b.Property<int>("Input");

                    b.Property<string>("Name");

                    b.Property<int>("Output");

                    b.HasKey("RepeaterId");

                    b.HasIndex("AttributesRepeaterAttributesId");

                    b.ToTable("Repeaters");
                });

            modelBuilder.Entity("UtahRepeaters.Api.Database.Models.RepeaterAttributes", b =>
                {
                    b.Property<int>("RepeaterAttributesId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ACTIVE");

                    b.Property<int>("AMSL_FEET");

                    b.Property<string>("ANT_INFO");

                    b.Property<string>("ARES");

                    b.Property<bool>("Autopatch");

                    b.Property<bool>("Bilingual");

                    b.Property<string>("CLOSED_PATCH");

                    b.Property<string>("CONTACT_EMAIL");

                    b.Property<string>("CONTACT_MAIL");

                    b.Property<string>("CONTACT_PHONE");

                    b.Property<DateTime>("COORD_DATE");

                    b.Property<string>("COORD_NOTES");

                    b.Property<string>("COVERAGE_AREA");

                    b.Property<int>("CTCSS_IN");

                    b.Property<int>("CTCSS_OUT");

                    b.Property<bool>("Closed");

                    b.Property<bool>("Coordinated");

                    b.Property<bool>("DCS");

                    b.Property<string>("DCS_CODE");

                    b.Property<bool>("DTMF");

                    b.Property<string>("EMERG_POWER");

                    b.Property<string>("EMERG_SUN");

                    b.Property<string>("EMERG_WIND");

                    b.Property<string>("ERP");

                    b.Property<bool>("Experimental");

                    b.Property<string>("FOOTNOTES");

                    b.Property<string>("GeographicalArea");

                    b.Property<bool>("INTERNET");

                    b.Property<string>("INTERNET_LINK");

                    b.Property<string>("LATITUDE_DDMMSS");

                    b.Property<string>("LAW");

                    b.Property<string>("LAW_DTMF");

                    b.Property<string>("LINKED");

                    b.Property<string>("LINKED_FREQ");

                    b.Property<bool>("LITZ");

                    b.Property<string>("LONGITUDE_DDDMMSS");

                    b.Property<string>("MAPSEL");

                    b.Property<string>("NOTES");

                    b.Property<bool>("Open");

                    b.Property<string>("PORTABLE");

                    b.Property<string>("PUB_CODE");

                    b.Property<string>("Patch_Seq");

                    b.Property<string>("RACES");

                    b.Property<string>("REPEATER_WEB_PAGE");

                    b.Property<bool>("Remote_Base");

                    b.Property<string>("SITE_NAME");

                    b.Property<bool>("SNP");

                    b.Property<string>("Source");

                    b.Property<string>("Sponsor");

                    b.Property<int>("TX_POWER");

                    b.Property<bool>("Tone");

                    b.Property<DateTime>("UPDATE");

                    b.Property<string>("UPDATE_SOURCE");

                    b.Property<string>("USE");

                    b.Property<string>("WEATHER");

                    b.Property<string>("WEATHER_DTMF");

                    b.Property<string>("WIDE_AREA");

                    b.HasKey("RepeaterAttributesId");

                    b.ToTable("RepeaterAttributes");
                });

            modelBuilder.Entity("UtahRepeaters.Api.Database.Models.Coordinates", b =>
                {
                    b.HasOne("UtahRepeaters.Api.Database.Models.Repeater", "Repeater")
                        .WithOne("Coordinates")
                        .HasForeignKey("UtahRepeaters.Api.Database.Models.Coordinates", "RepeaterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UtahRepeaters.Api.Database.Models.Repeater", b =>
                {
                    b.HasOne("UtahRepeaters.Api.Database.Models.RepeaterAttributes", "Attributes")
                        .WithMany()
                        .HasForeignKey("AttributesRepeaterAttributesId");
                });
#pragma warning restore 612, 618
        }
    }
}
